
// This is a file that should be ignored.
//
// <auto-generated />

using System;

namespace for_code_formatter
{
    class GeneratedTest
    {
        static void Run(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
